import { Injectable } from "@angular/core";
import { OrderInterface } from "../models/interfaces/order.interface";
import { ProductsComponent } from "../modules/portal/products/products.component";
import { UserService } from "./user.service";

@Injectable()
export class OrderService {
  constructor(private product: ProductsComponent, private user: UserService) {}
  orders: OrderInterface[] = [
    {
      id: 1001,
      productOrder: this.product[0],
      amount: 100,
      quantity: 50,
      orderedTo: this.user[0],
      orderedBy: this.user[1],
      orderDate: "01-01-2021",
      deliveryDate: "02-01-2021",
      address: "House No L-799 Sector 34/2 Korangi 3 Karachi",
      reciver: "Brother Asim",
    },
    {
      id: 1002,
      productOrder: this.product[1],
      amount: 90,
      quantity: 40,
      orderedTo: this.user[1],
      orderedBy: this.user[2],
      orderDate: "02-01-2021",
      deliveryDate: "03-01-2021",
      address: "Pakistan",
      reciver: "Sister",
    },
    {
      id: 1003,
      productOrder: this.product[2],
      amount: 200,
      quantity: 10,
      orderedTo: this.user[2],
      orderedBy: this.user[3],
      orderDate: "04-01-2021",
      deliveryDate: "05-02-2021",
      address: "Kalabagh",
      reciver: "Self",
    },
    {
      id: 1004,
      productOrder: this.product[4],
      amount: 300,
      quantity: 1000,
      orderedTo: this.user[4],
      orderedBy: this.user[3],
      orderDate: "05-02-2021",
      deliveryDate: "08-02-2021",
      address: "Sadar Karachi",
      reciver: "Self",
    },
    {
      id: 1005,
      productOrder: this.product[5],
      amount: 10,
      quantity: 10000,
      orderedTo: this.user[1],
      orderedBy: this.user[2],
      orderDate: "01-01-2021",
      deliveryDate: "02-01-2021",
      address: "Korangi Creek",
      reciver: "Uncle Furqan",
    },
    {
      id: 1006,
      productOrder: this.product[6],
      amount: 150,
      quantity: 200,
      orderedTo: this.user[0],
      orderedBy: this.user[1],
      orderDate: "09-01-2021",
      deliveryDate: "12-01-2021",
      address: "Landhi 36/B",
      reciver: "Self",
    },
    {
      id: 1007,
      productOrder: this.product[7],
      amount: 5,
      quantity: 10,
      orderedTo: this.user[1],
      orderedBy: this.user[0],
      orderDate: "02-02-2021",
      deliveryDate: "04-02-2021",
      address: "Malir Cant",
      reciver: "Nephew Adnan",
    },
    {
      id: 1008,
      productOrder: this.product[2],
      amount: 10,
      quantity: 15000,
      orderedTo: this.user[1],
      orderedBy: this.user[2],
      orderDate: "19-01-2021",
      deliveryDate: "21-01-2021",
      address: "Shah Faisal Town",
      reciver: "Self",
    },
    {
      id: 1009,
      productOrder: this.product[5],
      amount: 100,
      quantity: 50,
      orderedTo: this.user[0],
      orderedBy: this.user[1],
      orderDate: "01-01-2021",
      deliveryDate: "02-01-2021",
      address: "Ibrahim Haidre Goth",
      reciver: "Faisal Town",
    },
    {
      id: 1010,
      productOrder: this.product[8],
      amount: 100,
      quantity: 50,
      orderedTo: this.user[2],
      orderedBy: this.user[4],
      orderDate: "29-01-2020",
      deliveryDate: "15-02-2020",
      address: "Gulshan",
      reciver: "Self",
    },
  ];
}
